controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger1_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: Down
  - group: gripper
    pose: Open_gripper
